library(audio.whisper)
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-tiny.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-tiny.en.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-base.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-base.en.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-small.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-small.en.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-medium.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-medium.en.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-large.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
path  <- system.file(package = "audio.whisper", "models", "for-tests-ggml-large.en.bin")
model <- whisper(path)
  expect_inherits(model, class = "whisper")
  expect_inherits(model$model, class = "externalptr")
  expect_false(identical(model$model, new("externalptr")))
