# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

silero_vad <- function(path, vad_model, vad_threshold = 0.5, vad_min_speech_duration_ms = 250L, vad_min_silence_duration_ms = 100L, vad_max_speech_duration_s = -1, vad_speech_pad_ms = 30L, vad_samples_overlap = 0.1, use_gpu = FALSE, n_threads = 1L, probabilities = FALSE) {
    .Call('_audio_whisper_silero_vad', PACKAGE = 'audio.whisper', path, vad_model, vad_threshold, vad_min_speech_duration_ms, vad_min_silence_duration_ms, vad_max_speech_duration_s, vad_speech_pad_ms, vad_samples_overlap, use_gpu, n_threads, probabilities)
}

whisper_load_backend <- function() {
    invisible(.Call('_audio_whisper_whisper_load_backend', PACKAGE = 'audio.whisper'))
}

whisper_load_model <- function(model, use_gpu = FALSE, flash_attn = TRUE) {
    .Call('_audio_whisper_whisper_load_model', PACKAGE = 'audio.whisper', model, use_gpu, flash_attn)
}

whisper_encode <- function(model, path, language, token_timestamps = FALSE, translate = FALSE, duration = 0L, offset = 0L, trace = 1L, n_threads = 1L, n_processors = 1L, entropy_thold = 2.40, logprob_thold = -1.00, beam_size = -1L, best_of = 5L, split_on_word = FALSE, max_context = -1L, prompt = "", print_special = FALSE, diarize = FALSE, diarize_percent = 1.1, no_timestamps = FALSE, vad = FALSE, vad_model = "", vad_threshold = 0.5, vad_min_speech_duration_ms = 250L, vad_min_silence_duration_ms = 100L) {
    .Call('_audio_whisper_whisper_encode', PACKAGE = 'audio.whisper', model, path, language, token_timestamps, translate, duration, offset, trace, n_threads, n_processors, entropy_thold, logprob_thold, beam_size, best_of, split_on_word, max_context, prompt, print_special, diarize, diarize_percent, no_timestamps, vad, vad_model, vad_threshold, vad_min_speech_duration_ms, vad_min_silence_duration_ms)
}

whisper_print_benchmark <- function(model, n_threads = 1L) {
    invisible(.Call('_audio_whisper_whisper_print_benchmark', PACKAGE = 'audio.whisper', model, n_threads))
}

whisper_language_info <- function() {
    .Call('_audio_whisper_whisper_language_info', PACKAGE = 'audio.whisper')
}

