# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

whisper_encode <- function(model, path, language) {
    .Call('_audio_whisper_whisper_encode', PACKAGE = 'audio.whisper', model, path, language)
}

